# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc15e7434f1f1799c79d32df211110172fe6a292e1078d0dc5c215b6817b7873aeb427d595c1446969c37b4294ea81ab65addddfeacffd4a7d952d30e4f2537

test:
  secret_key_base: ec4b0d0f5b09e4f0e77ac3715b19fde0135a453b39de7ce47d49f4608d97efe523a8db2dccdef7092d0e1733dde09f7d4d14d8e6e5b9f38ed36032167a06e096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
